openapi: 3.2.0
info:
  title: Authologic Customer Database Verification API
  description: 'The integration API for using with Authlogic Engine.


    Authologic allows for simple and effective checking of the user''s identity, and the use of API enables initiation by an external system

    the verification process and the receipt of its results.'
  contact:
    name: API support
    email: tech-support@authologic.com
  version: '1.1'
servers:
- url: https://sandbox.authologic.com
  description: Testing environment
security:
- apiKey: []
- oauth2: []
tags:
- name: Database Verification
  description: '8. Product: Database Verification'
  externalDocs:
    description: Usage
    url: https://developer.authologic.com/docs/developer-documentation/product-dbv-index
paths:
  /api/conversations/{conversationId}/databaseVerification/info:
    get:
      tags:
      - Database Verification
      summary: Retrieving the database verification product information relating to the…
      description: 'Returns information about how the database verification process is performed for the given conversation ID.

        Results are available when the appropriate callback is received, or when the _databaseVerification_ status reaches _FINISHED_ OR _FAILED_.


        ## Response Content


        Detailed description of returned fields:


        | Parameter | Example | Description |

        |---------------------------------------| ------- | ----------- |

        |source| - | List of database verification source results. |

        |source.name|MATCHING| Type of the database verification use case (MATCHING). |

        |source.status|FINISHED| Processing status of the source (FINISHED / FAILED). |

        |source.sourceName|Australia Residential| Name of the source/database. |

        |source.sourceType|MARKETING| Type of the source/database (MARKETING / GOVERNMENT). |

        |source.sourceMatchResult|NO_MATCH| Overall match result (FULL_MATCH / PARTIAL_MATCH / NO_MATCH). |

        |source.errors|[SOURCE_UNAVAILABLE]| Information about the causes of errors. The content depends on the specific verification source. |'
      operationId: getDbV
      parameters:
      - name: conversationId
        in: path
        description: Conversation ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Database verification results available
          content:
            application/vnd.authologic.v1.1+json:
              schema:
                $ref: '#/components/schemas/DatabaseVerification'
        '400':
          description: Bad Request
          content:
            application/vnd.authologic.v1.1+json:
              schema:
                type: string
                oneOf:
                - $ref: '#/components/schemas/BadRequestApiError'
                - $ref: '#/components/schemas/MethodArgumentNotValidError'
                - $ref: '#/components/schemas/MethodArgumentTypeMismatchError'
                - $ref: '#/components/schemas/ConstraintViolationError'
                - $ref: '#/components/schemas/CustomValidationApiError'
                - $ref: '#/components/schemas/OperationNotSupportedApiFieldError'
                - $ref: '#/components/schemas/MissingHeaderApiError'
              example:
                status: BAD_REQUEST
                message: 'JSON body has an illegal format [Line: 10, Column: 12]: Unexpected character (''"'' (code 34)): was expecting Array entries.'
                violations: []
        '402':
          description: Exhaustion of the plan or limitations related to non-payment
        '403':
          description: Forbidden
          content:
            application/vnd.authologic.v1.1+json:
              schema:
                $ref: '#/components/schemas/ApiError'
              example:
                status: FORBIDDEN
                message: 'Permission denied for strategy: `public:b`.'
                violations: []
        '404':
          description: Conversation not found
          content:
            application/vnd.authologic.v1.1+json:
              schema:
                $ref: '#/components/schemas/ApiError'
              example:
                status: NOT_FOUND
                message: Item not found
                violations: []
        '410':
          description: Conversation is unavailable
          content:
            application/vnd.authologic.v1.1+json:
              schema:
                $ref: '#/components/schemas/ApiError'
              example:
                status: GONE
                message: Conversation is unavailable due to retention policy.
                violations: []
        '500':
          description: Server side error
components:
  schemas:
    CustomValidationApiError:
      type: object
      properties:
        status:
          type: string
          description: Response status
        message:
          type: string
          description: Descriptive error message
        violations:
          type: array
          description: Validation error list
          items:
            $ref: '#/components/schemas/Violation'
        statusDetail:
          type: string
          description: Response status detailed information
      required:
      - message
      - status
      - violations
    MethodArgumentTypeMismatchError:
      type: object
      properties:
        status:
          type: string
          description: Response status
        message:
          type: string
          description: Descriptive error message
        violations:
          type: array
          description: Validation error list
          items:
            $ref: '#/components/schemas/Violation'
        statusDetail:
          type: string
          description: Response status detailed information
      required:
      - message
      - status
      - violations
    DatabaseVerificationSource:
      type: object
      properties:
        name:
          type: string
          description: Type of the database verification use case
          enum:
          - MATCHING
          example: MATCHING
        status:
          type: string
          description: Processing status of the source
          enum:
          - FINISHED
          - FAILED
          example: FINISHED
        sourceName:
          type: string
          description: Name of the source/database
          example: Australia Residential
        sourceType:
          type: string
          description: Type of the source/database
          enum:
          - MARKETING
          - GOVERNMENT
          example: MARKETING
        sourceMatchResult:
          type: string
          description: Overall match result for the source
          enum:
          - FULL_MATCH
          - PARTIAL_MATCH
          - NO_MATCH
          example: FULL_MATCH
        errors:
          type: array
          description: Information about errors occurred when processing the request to the source database
          example: SERVICE_UNAVAILABLE
          items:
            type: string
      title: DatabaseVerificationSource
    OperationNotSupportedApiFieldError:
      type: object
      properties:
        status:
          type: string
          description: Response status
        message:
          type: string
          description: Descriptive error message
        violations:
          type: array
          description: Validation error list
          items:
            $ref: '#/components/schemas/Violation'
        statusDetail:
          type: string
          description: Response status detailed information
      required:
      - message
      - status
      - violations
    MethodArgumentNotValidError:
      type: object
      properties:
        status:
          type: string
          description: Response status
        message:
          type: string
          description: Descriptive error message
        violations:
          type: array
          description: Validation error list
          items:
            $ref: '#/components/schemas/Violation'
        statusDetail:
          type: string
          description: Response status detailed information
      required:
      - message
      - status
      - violations
    ApiError:
      type: object
      properties:
        status:
          type: string
          description: Response status
        message:
          type: string
          description: Descriptive error message
        violations:
          type: array
          description: Validation error list
          items:
            $ref: '#/components/schemas/Violation'
        statusDetail:
          type: string
          description: Response status detailed information
      required:
      - message
      - status
      - violations
    Violation:
      type: object
      properties:
        field:
          type: string
          description: Field name
        message:
          type: string
          description: Descriptive error message
      required:
      - field
      - message
    BadRequestApiError:
      type: object
      properties:
        status:
          type: string
          description: Response status
        message:
          type: string
          description: Descriptive error message
        violations:
          type: array
          description: Validation error list
          items:
            $ref: '#/components/schemas/Violation'
        statusDetail:
          type: string
          description: Response status detailed information
      required:
      - message
      - status
      - violations
    DatabaseVerification:
      type: object
      properties:
        source:
          type: array
          description: List of database verification source results
          items:
            $ref: '#/components/schemas/DatabaseVerificationSource'
      required:
      - source
      title: DatabaseVerification
    ConstraintViolationError:
      type: object
      properties:
        status:
          type: string
          description: Response status
        message:
          type: string
          description: Descriptive error message
        violations:
          type: array
          description: Validation error list
          items:
            $ref: '#/components/schemas/Violation'
        statusDetail:
          type: string
          description: Response status detailed information
      required:
      - message
      - status
      - violations
    MissingHeaderApiError:
      type: object
      properties:
        status:
          type: string
          description: Response status
        message:
          type: string
          description: Descriptive error message
        violations:
          type: array
          description: Validation error list
          items:
            $ref: '#/components/schemas/Violation'
        statusDetail:
          type: string
          description: Response status detailed information
      required:
      - message
      - status
      - violations
  securitySchemes:
    apiKey:
      type: http
      description: To log in, use the user's login and password. The password is the API key obtained for a specific environment. You can generate a new key in the API Keys section of the OmniPanel.
      scheme: basic
    oauth2:
      type: oauth2
      description: " To log in, use the user's login and password for client_id and client_secret, respectively. The password is the API key obtained for a specific environment. You can generate a new key in the API Keys section of the OmniPanel.\n \n Here is an example curl command for getting an access token:\n\n```bash\ncurl -i -X POST 'https://ENVIRONMENT_URL/api/oauth2/token' --header 'Authorization: Basic base64(user:pass)' --header 'Content-Type: application/x-www-form-urlencoded' -d 'grant_type=client_credentials'\n```\n\n**Note the following:**\n- use HTTP POST method while making the call\n- set the Content-Type header to application/x-www-form-urlencoded\n- pass in OAuth flow information: grant_type=client_credentials\n    Once the token has been received, it should be stored somewhere and can be used while making regular api calls.\n The OAuth calls should set the Authorization header as follows:\n \n ```http\nAuthorization: Bearer <token>\n```\n "
      scheme: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://sandbox.authologic.com/api/oauth2/token
          scopes: {}
externalDocs:
  description: API Documentation
  url: https://developer.authologic.com
